var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,g,k){if(f==Array.prototype||f==Object.prototype)return f;f[g]=k.value;return f};
$jscomp.getGlobal=function(f){f=["object"==typeof globalThis&&globalThis,f,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var g=0;g<f.length;++g){var k=f[g];if(k&&k.Math==Math)return k}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(f,g){var k=$jscomp.propertyToPolyfillSymbol[g];if(null==k)return f[g];k=f[k];return void 0!==k?k:f[g]};$jscomp.polyfill=function(f,g,k,m){g&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(f,g,k,m):$jscomp.polyfillUnisolated(f,g,k,m))};
$jscomp.polyfillUnisolated=function(f,g,k,m){k=$jscomp.global;f=f.split(".");for(m=0;m<f.length-1;m++){var t=f[m];if(!(t in k))return;k=k[t]}f=f[f.length-1];m=k[f];g=g(m);g!=m&&null!=g&&$jscomp.defineProperty(k,f,{configurable:!0,writable:!0,value:g})};
$jscomp.polyfillIsolated=function(f,g,k,m){var t=f.split(".");f=1===t.length;m=t[0];m=!f&&m in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var B=0;B<t.length-1;B++){var z=t[B];if(!(z in m))return;m=m[z]}t=t[t.length-1];k=$jscomp.IS_SYMBOL_NATIVE&&"es6"===k?m[t]:null;g=g(k);null!=g&&(f?$jscomp.defineProperty($jscomp.polyfills,t,{configurable:!0,writable:!0,value:g}):g!==k&&(void 0===$jscomp.propertyToPolyfillSymbol[t]&&(k=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[t]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(t):$jscomp.POLYFILL_PREFIX+k+"$"+t),$jscomp.defineProperty(m,$jscomp.propertyToPolyfillSymbol[t],{configurable:!0,writable:!0,value:g})))};$jscomp.underscoreProtoCanBeSet=function(){var f={a:!0},g={};try{return g.__proto__=f,g.a}catch(k){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(f,g){f.__proto__=g;if(f.__proto__!==g)throw new TypeError(f+" is not extensible");return f}:null;$jscomp.arrayIteratorImpl=function(f){var g=0;return function(){return g<f.length?{done:!1,value:f[g++]}:{done:!0}}};$jscomp.arrayIterator=function(f){return{next:$jscomp.arrayIteratorImpl(f)}};
$jscomp.makeIterator=function(f){var g="undefined"!=typeof Symbol&&Symbol.iterator&&f[Symbol.iterator];return g?g.call(f):$jscomp.arrayIterator(f)};$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(f){if(!(f instanceof Object))throw new TypeError("Iterator result "+f+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(f){this.yieldResult=f};$jscomp.generator.Context.prototype.throw_=function(f){this.abruptCompletion_={exception:f,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(f){this.abruptCompletion_={return:f};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(f){this.abruptCompletion_={jumpTo:f};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(f,g){this.nextAddress=g;return{value:f}};$jscomp.generator.Context.prototype.yieldAll=function(f,g){f=$jscomp.makeIterator(f);var k=f.next();$jscomp.generator.ensureIteratorResultIsObject_(k);if(k.done)this.yieldResult=k.value,this.nextAddress=g;else return this.yieldAllIterator_=f,this.yield(k.value,g)};
$jscomp.generator.Context.prototype.jumpTo=function(f){this.nextAddress=f};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(f,g){this.catchAddress_=f;void 0!=g&&(this.finallyAddress_=g)};$jscomp.generator.Context.prototype.setFinallyBlock=function(f){this.catchAddress_=0;this.finallyAddress_=f||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(f,g){this.nextAddress=f;this.catchAddress_=g||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(f){this.catchAddress_=f||0;f=this.abruptCompletion_.exception;this.abruptCompletion_=null;return f};$jscomp.generator.Context.prototype.enterFinallyBlock=function(f,g,k){k?this.finallyContexts_[k]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=f||0;this.finallyAddress_=g||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(f,g){g=this.finallyContexts_.splice(g||0)[0];if(g=this.abruptCompletion_=this.abruptCompletion_||g){if(g.isException)return this.jumpToErrorHandler_();void 0!=g.jumpTo&&this.finallyAddress_<g.jumpTo?(this.nextAddress=g.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=f};$jscomp.generator.Context.prototype.forIn=function(f){return new $jscomp.generator.Context.PropertyIterator(f)};
$jscomp.generator.Context.PropertyIterator=function(f){this.object_=f;this.properties_=[];for(var g in f)this.properties_.push(g);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var f=this.properties_.pop();if(f in this.object_)return f}return null};$jscomp.generator.Engine_=function(f){this.context_=new $jscomp.generator.Context;this.program_=f};
$jscomp.generator.Engine_.prototype.next_=function(f){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,f,this.context_.next_);this.context_.next_(f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(f){this.context_.start_();var g=this.context_.yieldAllIterator_;if(g)return this.yieldAllStep_("return"in g?g["return"]:function(k){return{value:k,done:!0}},f,this.context_.return);this.context_.return(f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(f){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],f,this.context_.next_);this.context_.throw_(f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(f,g,k){try{var m=f.call(this.context_.yieldAllIterator_,g);$jscomp.generator.ensureIteratorResultIsObject_(m);if(!m.done)return this.context_.stop_(),m;var t=m.value}catch(B){return this.context_.yieldAllIterator_=null,this.context_.throw_(B),this.nextStep_()}this.context_.yieldAllIterator_=null;k.call(this.context_,t);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var f=this.program_(this.context_);if(f)return this.context_.stop_(),{value:f.value,done:!1}}catch(g){this.context_.yieldResult=void 0,this.context_.throw_(g)}this.context_.stop_();if(this.context_.abruptCompletion_){f=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(f.isException)throw f.exception;return{value:f.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(f){this.next=function(g){return f.next_(g)};this.throw=function(g){return f.throw_(g)};this.return=function(g){return f.return_(g)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(f,g){g=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(g));$jscomp.setPrototypeOf&&f.prototype&&$jscomp.setPrototypeOf(g,f.prototype);return g};
$jscomp.asyncExecutePromiseGenerator=function(f){function g(m){return f.next(m)}function k(m){return f.throw(m)}return new Promise(function(m,t){function B(z){z.done?m(z.value):Promise.resolve(z.value).then(g,k).then(B,t)}B(f.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(f){return $jscomp.asyncExecutePromiseGenerator(f())};$jscomp.asyncExecutePromiseGeneratorProgram=function(f){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(f)))};
$jscomp.polyfill("Array.prototype.includes",function(f){return f?f:function(g,k){var m=this;m instanceof String&&(m=String(m));var t=m.length;k=k||0;for(0>k&&(k=Math.max(k+t,0));k<t;k++){var B=m[k];if(B===g||Object.is(B,g))return!0}return!1}},"es7","es3");$jscomp.initSymbol=function(){};$jscomp.iteratorPrototype=function(f){f={next:f};f[Symbol.iterator]=function(){return this};return f};
$jscomp.iteratorFromArray=function(f,g){f instanceof String&&(f+="");var k=0,m=!1,t={next:function(){if(!m&&k<f.length){var B=k++;return{value:g(B,f[B]),done:!1}}m=!0;return{done:!0,value:void 0}}};t[Symbol.iterator]=function(){return t};return t};$jscomp.polyfill("Array.prototype.values",function(f){return f?f:function(){return $jscomp.iteratorFromArray(this,function(g,k){return k})}},"es8","es3");$jscomp.owns=function(f,g){return Object.prototype.hasOwnProperty.call(f,g)};
$jscomp.polyfill("Object.entries",function(f){return f?f:function(g){var k=[],m;for(m in g)$jscomp.owns(g,m)&&k.push([m,g[m]]);return k}},"es8","es3");$jscomp.polyfill("Object.values",function(f){return f?f:function(g){var k=[],m;for(m in g)$jscomp.owns(g,m)&&k.push(g[m]);return k}},"es8","es3");
(function(f,g){"object"===typeof exports&&"undefined"!==typeof module?module.exports=g():"function"===typeof define&&define.amd?define(g):(f="undefined"!==typeof globalThis?globalThis:f||self,f.HlsP2P=g())})(this,function(){class f{constructor(){this.clientList=new Map}trigger(a,...b){if((a=this.clientList.get(a))&&0!==a.length)for(let c of a)c.apply(null,b)}listen(a,b){const c=this.clientList.get(a);if(!c)return this.clientList.set(a,[b]),this;for(a=c.length-1;0<=a;a--)if(c[a]===b)return this;c.push(b);
return this}remove(a,b){if(!a)return this.clientList.clear(),this;a=this.clientList.get(a);if(!a)return this;if(b)for(let c=a.length-1;0<=c;c--)a[c]===b&&a.splice(c,1);else a.length=0;return this}}class g{constructor(a=500,b=600){this.maxItmes=a;this.maxTtl=b;this.buffers=new Map;this.ttls=new Map;setInterval(()=>this.expire(),6E4)}hosts(){const a={};for(const [b,c]of this.buffers){const d=Array.from(c.keys());a[b]=d}return a}part(a){if(this.buffers.has(a))return this.buffers.get(a)}get(a,b){var c=
this.buffers.get(a);if(c&&(c=c.get(b)))return this.ttl(a,b),c}put(a){const {id:b,part:c}=a;this.ttl(b,c);var d=this.buffers.get(b);d?d.set(c,a):(d=new Map,d.set(c,a),this.buffers.set(b,d))}ttl(a,b){var c=this.ttls.get(a);c?c.set(b,Date.now()):(c=new Map,c.set(b,Date.now()),this.ttls.set(a,c))}expire(){let a=0;for(var [,b]of this.buffers)a+=b.size;if(!(a<=this.maxItmes)){b=Date.now();for(const [c,d]of this.ttls){for(const [e,h]of d)if(b-h>this.maxTtl){d.delete(e);const l=this.buffers.get(c);if(l&&
(l.delete(e),a--<this.maxItmes))break}d.size||(this.buffers.delete(c),this.ttls.delete(c))}}}}const k=new g;let m="";const t=()=>{if(m)return m;m=sessionStorage.getItem("uid");if(!m||36!=m.length){function a(){return(65536*(1+Math.random())|0).toString(36)}m=a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a();sessionStorage.setItem("uid",m)}return m},B=sessionStorage.getItem("loglevel")||"",z=["warn","info","log"].includes(B)?console.warn.bind(console):()=>{},T=["info","log"].includes(B)?console.info.bind(console):
()=>{},C=["log"].includes(B)?console.log.bind(console):()=>{},G=a=>$jscomp.asyncExecutePromiseGeneratorFunction(function*(){return new Promise(b=>{setTimeout(b,a)})}),N=a=>{var b=a.reduce((d,e)=>d+e.byteLength,0);b=new Uint8Array(b);let c=0;for(const d of a)b.set(new Uint8Array(d),c),c+=d.byteLength;return b.buffer},O=(a,b)=>{if(a.size!==b.size)return!1;for(const c of a)if(!b.has(c))return!1;return!0},D=(...a)=>{const b=window;b.__hls_p2p_stat&&Array.isArray(b.__hls_p2p_stat)&&b.__hls_p2p_stat.forEach(c=>
c.$emit(...a))};class U extends f{constructor(a){super();this.addr=a;this.$ws=null;this.tasks=[];this.runing=!1;this.connect()}destroy(){this.stopconnect();this.connect=()=>{};this.startconnect=()=>{};this.notify=()=>{};this.sendJson=a=>{console.error("closed");return this};this.$ws&&this.$ws.close()}connect(){!this.$ws||this.$ws.readyState!=this.$ws.OPEN&&this.$ws.readyState!=this.$ws.CONNECTING?(this.$ws=new WebSocket(this.addr),this.$ws.binaryType="arraybuffer",this.$ws.onopen=a=>{this.trigger("open",
a);this.stopconnect();this.notify()},this.$ws.onmessage=a=>{this.trigger("message",a)},this.$ws.onclose=a=>{console.log(a,a.reason,a.toString());this.trigger("close",a);this.startconnect()},this.$ws.onerror=a=>{console.warn(a,a.toString());this.trigger("error",a);this.startconnect()}):this.stopconnect()}startconnect(){clearInterval(this.timer);this.timer=setInterval(()=>{!1!==navigator.onLine&&this.connect()},2E3)}stopconnect(){clearInterval(this.timer)}notify(){if(!this.runing){this.runing=!0;if(this.$ws&&
this.$ws.readyState==this.$ws.OPEN){let a;for(;a=this.tasks.shift();)this.$ws.send(a)}else this.startconnect();this.runing=!1}}send(a){this.$ws&&this.$ws.send(a);return this}sendJson(a){try{const b=JSON.stringify(a);b&&(this.tasks.push(b),this.notify())}catch(b){console.error(b)}return this}}let J;var P=a=>{J||(J=new U(a+t()),J.listen("message",b=>{try{if("string"==typeof b.data){const c=JSON.parse(b.data);return c.event?J.trigger(c.event,c):console.warn(c)}return console.warn(b.data)}catch(c){console.error(c)}}));
return J};const K=[115,99],V=a=>{var b=new Uint8Array(a);if(4>b.length)throw Error("bad msg");if(b[0]!==K[0]||b[1]!==K[1])throw Error("mismatch protocol");if(161!==b[2])throw Error("mismatch version");var c=b[3];b=b.slice(4,4+c);a=a.slice(4+c);c=String.fromCharCode.apply(null,b);const [d,e,h,l]=JSON.parse(c);return{id:d,sn:e,i:h,n:l,data:a,t:Date.now()}},W=a=>{if(!a.startsWith("ss"))return!1;const [b,c]=a.substring(a.length-2).split("").map(d=>d.charCodeAt(0));return a.substring(2,a.length-2).split("").reduce((d,
e)=>d+e.charCodeAt(0),0)%b==c};let Q;class X{constructor(a,b,c){this.id=a;this.opts=b;this.trigger=c;this.speed=this.activetime=this.createtime=this.restart=this.rx=this.tx=0;this.relay=!1;this.buffers=new Map;this.responseParts=this.resolveParts=0;this.hosts={};this.resolveTasks=[];this.queryTasks=[];this.bufferQueue=[];this.queuerunning=!1;this.me=t();this.isServer=W(a);this.$ws=P(b.tracker);this.init();this.resolveTaskTimer=setInterval(()=>this.doTask(),600+200*Math.random())}destroy(){clearInterval(this.resolveTaskTimer);
clearInterval(this.hostsTimer);try{this.dc&&this.dc.close(),this.c&&this.c.close()}catch(a){C(a)}}get cansend(){return this.dc&&"open"==this.dc.readyState}init(){if(this.c)try{this.c.close()}catch(a){C(a)}this.createtime=Date.now();this.c=new RTCPeerConnection(this.opts.rtcConf);this.c.onnegotiationneeded=a=>{const b=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){C(a);try{const c=yield b.c.createOffer();b.$ws.sendJson({event:"offer",to:b.id,from:b.me,data:c});yield b.c.setLocalDescription(c)}catch(c){z(c)}})};
this.c.ondatachannel=a=>{if(this.dc)try{this.dc.close()}catch(b){C(b)}this.dc=a.channel;this.dc.binaryType="arraybuffer";this.dc.bufferedAmountLowThreshold=61440;this.dcInit();C(a)};this.c.onconnectionstatechange=a=>{C(a)};this.c.onicecandidateerror=a=>{z(a)};this.c.onicegatheringstatechange=a=>{C(a)};this.c.oniceconnectionstatechange=a=>{C(a)};this.c.onicecandidate=a=>{a.candidate&&("host"==a.candidate.type&&(this.localAddress=a.candidate.address,this.localPort=a.candidate.port),"srflx"==a.candidate.type&&
(this.localAddress=Q=a.candidate.address,this.localPort=a.candidate.port),"relay"==a.candidate.type&&(this.relatedAddress=a.candidate.address,this.relatedPort=a.candidate.port),this.$ws.sendJson({event:"candidate",from:this.me,to:this.id,data:a.candidate}))}}waitForConnect(){}doTask(){const a=Date.now();this.resolveTasks=this.resolveTasks.filter(c=>{const d=k.get(c.id,c.sn);d&&this.cansend&&setTimeout(()=>this.callQueue(d),0);return 6E4<a-c.t?!1:!0});const b=new Map;this.queryTasks=this.queryTasks.filter(c=>
{if(k.get(c.id,c.sn)){const d=b.get(c.id);d?d.add(c.sn):b.set(c.id,new Set([c.sn]));return!1}return 6E4<a-c.t?!1:!0});if(this.cansend){for(const [c,d]of b){const e=JSON.stringify({event:"quit",data:{id:c,parts:Array.from(d)}});this.send(e);this.resolveParts-=d.size}this.packet=this.calcPacket()}}connect(){clearTimeout(this.restart);this.init();if(this.dc)try{this.dc.close()}catch(a){z(a)}this.dc=this.c.createDataChannel("dc",{maxPacketLifeTime:9E3,ordered:!1});this.dc.binaryType="arraybuffer";this.dc.bufferedAmountLowThreshold=
61440;this.dcInit()}checkConn(){if(this.c&&"connected"==this.c.connectionState&&this.cansend){const a=JSON.stringify({event:"ping"});this.send(a);C(a);clearTimeout(this.restart);this.restart=setTimeout(()=>this.connect(),5E3)}else this.connect()}sendHosts(a=!1){if(this.cansend&&!this.isServer){var b=k.hosts();b=JSON.stringify({event:"hosts",data:b});if(a||b!=this.selfHosts)this.send(b),this.selfHosts=b}}dcInit(){const a=()=>{this.destroy()};window.addEventListener("pagehide",a);window.addEventListener("beforeunload",
a);window.addEventListener("unload",a);this.dc.onopen=b=>{this.isUsedRelay();this.trigger("open",{id:this.id,data:b});this.activetime=Date.now();this.sendHosts(!0);clearInterval(this.hostsTimer);this.hostsTimer=setInterval(()=>this.sendHosts(),15E3)};this.dc.onclose=b=>{z("dc close "+this.id,b);this.trigger("close",{id:this.id,data:b})};this.dc.onerror=b=>{z("dc error "+this.id,b);this.trigger("error",{id:this.id,data:b})};this.dc.onbufferedamountlow=()=>{};this.dc.onmessage=b=>{const c=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){clearTimeout(c.restart);
let d=b.data;d instanceof Blob&&(d=yield b.data.arrayBuffer());c.rx=d instanceof ArrayBuffer?c.rx+d.byteLength:c.rx+d.length;c.activetime=Date.now();c.extract(d)})}}extract(a){if(!(a instanceof ArrayBuffer)){var b=JSON.parse(a);switch(b.event){case "hosts":this.hosts=b.data;return;case "ping":var c=JSON.stringify({event:"pong"});this.send(c);return;case "pong":return;case "resolve":a=b.data.id;b=b.data.parts;var d=Date.now();for(c of b)this.resolveTasks.push({id:a,t:d,sn:c});this.doTask();return;
case "quit":const h=b.data.id,l=b.data.parts;this.resolveTasks=this.resolveTasks.filter(n=>n.id==h&&l.includes(n.sn)?!1:!0);return}return this.trigger("message",{data:a,id:this.id})}const e=V(a);c=e.id+":"+e.sn;(a=this.buffers.get(c))?a[e.i]=e:(a=[],a[e.i]=e,this.buffers.set(c,a));this.queryTasks=this.queryTasks.filter(h=>h.id==e.id&&h.sn==e.sn?!1:!0);this.trigger("buffer.recv",{data:e,id:this.id});a=!0;b=this.buffers.get(c);for(d=0;d<e.n;d++)if(!b[d]){a=!1;break}if(a){a=N(b.map(h=>h.data));b=b.map(h=>
h.t);this.buffers.delete(c);c=Math.max(...b)-Math.min(...b);this.speed=Math.round(a.byteLength/1024/(1>c?1:c/1E3));c=k.get(e.id,e.sn);if(b=!c)c={id:e.id,part:e.sn,buffer:a},k.put(c);this.responseParts++;this.trigger("buffer",{data:c,newly:b,server:this.isServer,id:this.id});C("\u63a5\u6536\u5206\u7247",e.sn,"\u6765\u81ea",this.id,"\u901f\u5ea6",this.speed,"newly",b)}}callQueue(a){const b=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){b.bufferQueue.find(c=>c.id==a.id&&c.part==
a.part)||b.bufferItemSending&&b.bufferItemSending.id==a.id&&b.bufferItemSending.part==a.part||b.bufferQueue.push(a);if(!b.queuerunning)try{for(b.queuerunning=!0;b.bufferItemSending=b.bufferQueue.shift();){if(!b.dc||!b.cansend){b.bufferQueue.length=0;break}for(;61440<b.dc.bufferedAmount;)yield G(500);b.resolveTasks.find(c=>c.id==b.bufferItemSending.id&&c.sn==b.bufferItemSending.part)&&(b.sendBuffer(b.bufferItemSending),b.resolveTasks=b.resolveTasks.filter(c=>!(c.id==b.bufferItemSending.id&&c.sn==b.bufferItemSending.part)))}}finally{b.queuerunning=
!1}})}calcPacket(){let a=0;for(const [,b]of this.buffers){let c=!0;const d=b.find(e=>e);if(d){for(let e=0;e<d.n;e++)if(!b[e]){c=!1;break}c||a++}}return a}sendBuffer(a){const b=this.splitBuffer(a);for(let c=0;c<b.length;c++)this.send(b[c]);D("rtc-sent",this.id,a)}splitBuffer(a){let b=0,c=!1;const d=a.buffer.byteLength,e=[],h=Math.ceil(d/61440);for(;;){var l=61440*b,n=61440*(b+1);n>=d&&(n=d,c=!0);var r=a.buffer.slice(l,n);l=e;n=l.push;var v=JSON.stringify([a.id,a.part,b,h]),w=(new Uint8Array([K[0],
K[1],161,v.length])).buffer;const E=new ArrayBuffer(v.length),u=new Uint8Array(E);for(let x=0,A=v.length;x<A;x++)u[x]=v.charCodeAt(x);r=N([w,E,r]);n.call(l,r);b++;if(c)return e}}onOffer(a){const b=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){yield b.c.setRemoteDescription(a);if(["closed","stable"].includes(b.c.signalingState))z("onOffer error signalingState is "+b.c.signalingState);else{var c=yield b.c.createAnswer();b.$ws.sendJson({event:"answer",from:b.me,to:b.id,data:c});
yield b.c.setLocalDescription(c)}})}onAnswer(a){const b=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){["closed","stable"].includes(b.c.signalingState)?z("onAnswer error signalingState is "+b.c.signalingState):yield b.c.setRemoteDescription(a)})}onCandidate(a){const b=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){var c=(c=a.candidate.match(/:(\d+)\s+\d\s+([a-zA-Z]{3})\s+(\d+)\s+([\w\-\.]+)\s+(\d+)\s+typ\s+([a-z]+)(?:\s+raddr\s+([\w\-\.]+)\s+rport\s+(\d+)(?:.+ufrag\s+(\w+))?)?/))?
{foundation:c[1],protocol:c[2],priority:c[3],address:c[4],port:c[5],type:c[6],relatedAddress:c[7],relatedPort:c[8],usernameFragment:c[9]}:null;c&&("host"==c.type&&(b.remoteAddress=c.address,b.remotePort=Number(c.port)),"srflx"==c.type&&(b.remoteAddress=c.address,b.remotePort=Number(c.port)),"relay"==c.type&&(b.relatedAddress=c.address,b.relatedPort=Number(c.port)));["closed"].includes(b.c.signalingState)?z("onCandidate error signalingState is "+b.c.signalingState):(b.c.remoteDescription||(yield G(200)),
yield b.c.addIceCandidate(a))})}resolve(a,b){const c=new Set;var d=this.get_want(a),e=[];for(const h of b)e.push(this.isServer?{part:h.sn,url:h.url}:h.sn),d.has(h.sn)&&c.add(h);d=JSON.stringify({event:"resolve",data:{id:a,parts:e}});this.send(d);this.resolveParts+=e.length;e=Date.now();for(const h of b)this.queryTasks.push({id:a,t:e,sn:h.sn});return c}get_want(a){const b=new Set;this.resolveTasks.forEach(({id:c,sn:d})=>{a==c&&b.add(d)});return b}send(a){if(this.dc)if("open"!==this.dc.readyState)C("data channel to "+
this.id+" is not open");else try{const b=this.dc.send(a);this.tx=a instanceof ArrayBuffer?this.tx+a.byteLength:this.tx+a.length;return b}catch(b){z(b),this.connect()}else C("data channel to "+this.id+" is not avaiable")}isUsedRelay(){const a=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){const b=yield a.c.getStats();let c="";for(const {type:e,state:h,localCandidateId:l}of b.values())if("candidate-pair"===e&&"succeeded"===h&&l){c=l;break}let d;a.relay=!!c&&"relay"===(null==(d=
b.get(c))?void 0:d.candidateType);a.relay&&z("relay found",a,c);return a.relay})}stat(){return{tx:this.tx,rx:this.rx,state:this.dc?this.dc.readyState:null,cstate:this.c?this.c.connectionState:null,istate:this.c?this.c.iceConnectionState:null,gstate:this.c?this.c.iceGatheringState:null,bufferedAmount:this.dc?this.dc.bufferedAmount:0,createtime:this.createtime,activetime:this.activetime,isServer:this.isServer,speed:this.speed,hosts:this.hosts,localAddress:this.localAddress||Q,localPort:this.localPort,
remoteAddress:this.remoteAddress,remotePort:this.remotePort,relay:this.relay,relatedAddress:this.relatedAddress,relatedPort:this.relatedPort,packet:this.packet,resolveParts:this.resolveParts,responseParts:this.responseParts}}}const F=new Map;class Y extends f{constructor(a){super();this.opts=a;this.enable=!1;this.hostIds=new Set;this.wsIds=new Set;this.me=t();this.resolving=new Map;this.respstat=new Map;this.disabledPeers=new Map;a.tracker&&"function"==typeof window.RTCPeerConnection&&(this.$ws=P(a.tracker),
this.init(),setInterval(()=>{var b=this.getStats();Object.keys(b).length&&D("peers",b);b=[];const c=Date.now();for(const [d,e]of this.resolving)k.get(this.opts.id,d)?this.resolving.delete(d):6E4<=c-e.t&&b.push(e.fragment);b.length&&this.req(b)},2E3),this.enable=!0)}req(a){if(!this.enable)return{unresolved_retry:[],guessed_retry:[],unresolved:a,guessed:[],guessed_eachother:[]};var b=this.opts.buffered();this.join(this.opts.id);const c=Date.now();var d=Math.floor(c/1E3/60),e=d%3,h=[...a],l=this.getStats();
const n=[],r=[];for(const [p,q]of Object.entries(l)){if("open"!==q.state||"connected"!==q.cstate)continue;l=F.get(p);if(!l)continue;if(0>=q.speed&&5<q.packet)continue;var v=this.disabledPeers.get(p),w=!1;if(v){if(v===d)continue;w=!0;this.disabledPeers.delete(p)}if((0==h.length||0<n.length)&&(q.relay||0<q.speed&&60>q.speed||3<q.packet)&&!w){this.disabledPeers.set(p,d);continue}v=this.respstat.get(p)||[];v[e]=q.resolveParts?q.responseParts/q.resolveParts:1;this.respstat.set(p,v);if(v.every(L=>.2>L))continue;
if(q.isServer){n.push({peer:l,stat:q,blocks:[]});continue}const y=q.hosts[this.opts.id];!y||1>y.length||(r.push({peer:l,stat:q,blocks:y}),h=h.filter(L=>!y.includes(L.sn)))}d=(p,q)=>{var y=q.stat.speed-p.stat.speed;if(0!=y)return y;y=p.stat.packet-q.stat.packet;return 0!=y?y:p.stat.relay!==q.stat.relay?p.stat.relay?1:-1:p.stat.rx-q.stat.rx};r.sort(d);n.sort(d);const E=new Map;d=[];e=[];l=[];v=[];let u=w=0;const x=(p,q)=>{const y=E.get(p);y?y.add(q):E.set(p,new Set([q]))};b=15E3+200*Math.random()*b;
for(const p of a){a=this.resolving.get(p.sn);var A=h.find(q=>q.sn==p.sn),H=a&&c-a.t>b;if(!(a&&c-a.t<b)||a.guess&&!A)if(A)if(H){H=A=!1;for(const q of n)if(q.peer.id!=a.uid){x(q.peer,p);A=!0;break}if(!A&&r.length){const q=this.sort_guess_client(p.sn,r);for(const y of q)if(y.peer.id!==a.uid){x(y.peer,p);H=!0;break}}A||H?H&&v.push(p):l.push(p)}else a=this.sort_guess_client(p.sn,r,10),a.length?(x(a[0].peer,p),e.push(p)):n.length?(w>=n.length&&(w=0),x(n[w].peer,p),w++):r.length?(a=this.sort_guess_client(p.sn,
r),a.length?(x(a[0].peer,p),e.push(p)):d.push(p)):d.push(p);else if(H){A=!1;for(const q of r)if(q.blocks.find(y=>y==p.sn)&&q.peer.id!=a.uid){x(q.peer,p);A=!0;break}if(!A&&n.length)for(const q of n)if(q.peer.id!=a.uid){x(q.peer,p);A=!0;break}if(!A&&r.length){H=this.sort_guess_client(p.sn,r);for(const q of H)if(q.peer.id!==a.uid){x(q.peer,p);v.push(p);A=!0;break}}A||l.push(p)}else{u>=r.length&&(u=0);for(a=!1;u<r.length;u++)if(A=r[u],A.blocks.find(q=>q==p.sn)){x(A.peer,p);a=!0;u++;break}if(!a)for(u=
0;u<r.length;u++)if(A=r[u],A.blocks.find(q=>q==p.sn)){x(A.peer,p);a=!0;u++;break}a||(console.error("not found in all clients_arr",p,r),d.push(p))}}const Z=e.map(p=>p.sn),R=new Set;for(const [p,q]of E)p.resolve(this.opts.id,q).forEach(y=>R.add(y)),q.forEach(y=>{this.resolving.set(y.sn,{t:c,uid:p.id,guess:Z.includes(y.sn),fragment:y})});h=Array.from(R);return{unresolved:d,guessed:e,unresolved_retry:l,guessed_retry:v,guessed_eachother:h}}sort_guess_client(a,b,c=30){const d=[],e={};for(const h of b){b=
c;for(const l of h.blocks){const n=a-l;0<=n&&n<b&&(b=n)}b<c&&(e[h.peer.id]=b,d.push(h))}return d.sort((h,l)=>e[h.peer.id]-e[l.peer.id])}init(){this.$ws.listen("offer",a=>this.onOffer(a.from,a.data)).listen("answer",a=>this.onAnswer(a.from,a.data)).listen("candidate",a=>this.onCandidate(a.from,a.data)).listen("online",a=>{a.id!=this.me&&this.toConnect(a.id)}).listen("init",a=>this.waitIds(new Set(a.ids))).listen("open",()=>{this.hostIds.size&&!O(this.hostIds,this.wsIds)&&(this.$ws.sendJson({event:"join",
ids:[...this.hostIds]}),this.wsIds=new Set(this.hostIds))}).listen("close",()=>{this.wsIds=new Set}).listen("error",()=>{this.wsIds=new Set})}join(a){this.hostIds.add(a);O(this.hostIds,this.wsIds)||(this.$ws.sendJson({event:"join",ids:[...this.hostIds]}),this.wsIds=new Set(this.hostIds))}getPeers(){return F.keys()}getStats(){const a=Date.now(),b={},c=100<F.size?6E4:3E5;F.forEach(d=>{const e=d.stat();a-e.createtime>c&&a-(e.activetime||e.createtime)>c&&("open"!==e.state||"connected"!==e.cstate)?(d.destroy(),
F.delete(d.id)):b[d.id]=e});return b}newPeer(a,b){const c=new X(a,this.opts,(d,e)=>this.trigger(d,e));F.set(a,c);b?c.waitForConnect():c.checkConn();return c}waitIds(a){a.forEach(b=>{if(b!=this.me){var c=F.get(b);c?c.waitForConnect():this.newPeer(b,!0)}})}toConnect(a){const b=F.get(a);b?b.checkConn():this.newPeer(a,!1)}onOffer(a,b){const c=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){let d=F.get(a);d||(d=c.newPeer(a,!0),z(`recreate ${a} in onOffer`));d.onOffer(b)})}onAnswer(a,
b){const c=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){let d=F.get(a);d||(d=c.newPeer(a,!0),z(`recreate ${a} in onAnswer`));d.onAnswer(b)})}onCandidate(a,b){const c=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){let d=F.get(a);d||(d=c.newPeer(a,!0),z(`recreate ${a} in onCandidate`));d.onCandidate(b)})}}class aa extends Y{constructor(a){super(a)}}var I;(function(a){a.BASE64="base64";a.QUERY="query"})(I||(I={}));class ba{fetch(a,b){const c=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){const d=
new Request(a.url,{method:"GET"});return yield c.send(d,b,a)})}send(a,b,c){return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){let d=null,e,h,l=!1;const n=Date.now()+b.timeout/2;"function"==typeof AbortController&&(e=new AbortController,d=e.signal);const r=new Promise((w,E)=>{const u=setInterval(()=>{if(h)return w(h),e&&e.abort(),clearInterval(u);const x=k.get(c.id,c.data.sn);if(x)return h={data:x.buffer,newly:!1,cached:!0},w(h),e&&e.abort(),clearInterval(u);if(!l&&Date.now()>n)return e&&
e.abort(),E("ttfb timeout"),clearInterval(u)},500);setTimeout(()=>{clearInterval(u);h&&w(h);e&&e.abort();h||E("timeout")},b.timeout)}),v=new Promise((w,E)=>{fetch(a,{signal:d,cache:b.cache?"force-cache":"reload"}).then(u=>{l=!0;const x=k.get(c.id,c.data.sn);if(x)return h={data:x.buffer,newly:!1,cached:!0},w(h),e&&e.abort(),x.buffer;if(!u.ok)throw Error(`${u.url} : ${u.statusText||u.status}`);return u.arrayBuffer()}).then(u=>{if(h)return w(h);const x=k.get(c.id,c.data.sn);h={data:u,newly:!x,cached:!1};
w(h)}).catch(E)});return yield Promise.race([v,r])})}}class ca{constructor(a){this.opts=a;this.fetchInstance=new ba;this.mirrors={};this.mirrorOpts={};this.times={};this.errors={};this.index=0;this.mirrorLoaded={};this.originErrors=this.originCosts=this.originTimes=this.originLoaded=0;this.defaultMirrorType=I.QUERY;this.fastMirrors=[];this.sortedMirrors=[];this.allSortedMirrors=[];if(Array.isArray(a.mirrors)&&a.mirrors.length)for(const b of a.mirrors){let c,d=!1;if("string"==typeof b)a=b,c=this.defaultMirrorType;
else{if(!b||!b.url)continue;a=b.url;c=b.type||this.defaultMirrorType;d=!!b.fast}this.mirrors[a]=0;this.times[a]=0;this.mirrorOpts[a]={url:a,type:c,fast:d};d?this.fastMirrors.push({url:a,value:0}):this.sortedMirrors.push({url:a,value:0});this.allSortedMirrors.push({url:a,value:0})}}retry(a,b,c){return()=>{const d=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){const e={no:c.sn,data:new ArrayBuffer(0),err:Error("unresolved"),newly:!1,cached:!1};var h=k.get(d.opts.id,c.sn);if(h)return e.data=
h.buffer,e.newly=!1,e.cached=!0,e.err=null,e;const l={timeout:15E3,cache:!0};let n;for(let r=0;r<a;r++){h=b();try{l.timeout=h.timeout;n=Date.now();const v=yield d.fetchInstance.fetch(h,l);e.data=v.data;e.err=null;e.newly=v.newly;e.cached=v.cached;const w=e.data?e.data.byteLength:-1;if(0>=w)throw e.err=Error(`short read error,got ${w}`),e.err;k.put({id:d.opts.id,part:c.sn,buffer:e.data});d.stat(h.mirror,Date.now()-n,e.cached?0:w);break}catch(v){d.stat(h.mirror,2E4,0);const w=k.get(d.opts.id,c.sn);
if(w){T("http error but rtc ok",c);e.err=null;e.data=w.buffer;e.newly=!1;e.cached=!0;break}l.cache=!1;z(v,r,h,c);e.err=v;yield G(200)}finally{D("mirrors",d.mirrors,d.times,d.errors,d.mirrorLoaded,d.originLoaded,d.originTimes,d.originCosts,d.originErrors)}}return e})}}req(a){const b=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){var c=b.getURLFn(a);c=yield b.retry(5,c,a)();if(c.err)throw c.err;return c})}getStats(){return{mirrors:this.mirrors,times:this.times,errors:this.errors,
mirrorLoaded:this.mirrorLoaded,originLoaded:this.originLoaded,originTimes:this.originTimes,originCosts:this.originCosts,originErrors:this.originErrors}}getURLFn(a){let b=!1;const c=[];return()=>{const d=this.opts.buffered();var e;if(10>d||!this.sortedMirrors.length)if(e=this.bestFast(c))e=e.url;else{if(!b||!this.allSortedMirrors.length)return b=!0,{id:this.opts.id,url:a.url,data:a,mirror:"",timeout:2E4};e=this.getBestMirror(this.allSortedMirrors,c,d);c.length||(b=!1)}else e=this.getBestMirror(this.sortedMirrors,
c,d);c.push(e);let h=2E4;20>d?h=12E3:30>d&&(h=14E3);return{id:this.opts.id,url:this.buildURL(e,a.url),data:a,mirror:e,timeout:h}}}bestFast(a){let b=null;for(const [d,e]of Object.entries(this.mirrors))b?e<b.value&&3<=this.times[d]&&!a.includes(d)&&(b={url:d,value:e}):b={url:d,value:e};const c=Math.min(5E3,Math.max(2E3,this.originCosts));return b&&b.value<c&&3<=this.times[b.url]&&!a.includes(b.url)?b:null}getBestMirror(a,b,c){var d=Object.keys(this.mirrors).filter(e=>!this.times[e]);if(d.length)return d[this.index++%
d.length];d=a.map(e=>e.url);a=d.filter(e=>!b.includes(e));a.length||(b.length=0,a=d);d=[];for(const e of a){const h=this.times[e],l=this.mirrors[e];0<l&&18E3>l?l<250*c&&d.push(e):3>h&&60<c&&d.push(e)}1>d.length&&d.push(...a.slice(0,2));c=this.index++%d.length;return d[c]}stat(a,b,c){if(a){this.mirrorLoaded[a]=this.mirrorLoaded[a]?this.mirrorLoaded[a]+c:c;this.times[a]++;2E4<=b&&0==c&&(this.errors[a]?this.errors[a]++:this.errors[a]=1);this.mirrors[a]=Math.round((this.mirrors[a]+b)/2);a=[];b=[];c=[];
for(const [d,e]of Object.entries(this.mirrors))c.push({url:d,value:e}),this.mirrorOpts[d]&&this.mirrorOpts[d].fast?b.push({url:d,value:e}):a.push({url:d,value:e});c.sort((d,e)=>d.value-e.value);this.allSortedMirrors=c;a.sort((d,e)=>d.value-e.value);this.sortedMirrors=a;b.sort((d,e)=>d.value-e.value);this.fastMirrors=b}else this.originLoaded+=c,this.originTimes++,this.originCosts=Math.round((this.originCosts+b)/2),2E4<=b&&0==c&&this.originErrors++}buildURL(a,b){const c=this.mirrorOpts[a]?this.mirrorOpts[a]:
this.defaultMirrorType;return c==I.BASE64||c.type==I.BASE64?(b=btoa(Array.from((new TextEncoder).encode(b)).map(d=>String.fromCharCode(d)).join("")),"/"==a[a.length-1]?a+b:a+"/"+b):a+"?u="+b}}class da extends f{constructor(a){super();this.opts=a;this.rtcTotalDownload=this.rtcServerDelayDownload=this.rtcClientDelayDownload=this.rtcServerDownload=this.rtcClientDownload=this.httpTotalDownload=0;this.tasks=new Map;this.lastReportTime=this.httpThread=0;this.is_rtc_peers_alive=!1;if(a.statURL){let b=!1;
const c=()=>{if(!b){var d=this.getStatData();if(!(1>Object.values(d).reduce((h,l)=>h+l))){var e=this.httpProvider.getStats();d=JSON.stringify(Object.assign({},a.params,{id:a.id,httpData:e,statData:d}));navigator.sendBeacon?navigator.sendBeacon(a.statURL,d)||fetch(a.statURL,{method:"POST",body:d,keepalive:!0}):fetch(a.statURL,{method:"POST",body:d,keepalive:!0});b=!0}}};window.addEventListener("pagehide",c);window.addEventListener("beforeunload",c);window.addEventListener("unload",c)}this.httpProvider=
new ca(a)}req(a){const b=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){var c=k.get(b.opts.id,a.sn);if(c)return c;c=b.tasks.get(a.sn);try{if(!c){let d;c=new Promise((e,h)=>$jscomp.asyncExecutePromiseGeneratorFunction(function*(){let l=0;try{if(!(45>b.opts.buffered())&&b.is_rtc_peers_alive)for(b.rtcReq([a]);35<b.opts.buffered();){yield G(200);const n=k.get(b.opts.id,a.sn);if(n)return d=n,e(d);if(!b.is_rtc_peers_alive)break}b.httpThread++;l=1;d=yield Promise.race(b.buildReq(a));
return e(d)}catch(n){return h(n)}finally{b.httpThread-=l}}));b.tasks.set(a.sn,c)}return yield c}finally{b.tasks.delete(a.sn)}})}buildReq(a){return[new Promise(b=>{const c=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){let d=!1,e=0;for(;;){yield G(200);const h=k.get(c.opts.id,a.sn);if(h)return b(h);50<e++&&!d&&(c.rtcReq([a]),d=!0)}})}),this.httpReq(a)]}next(a,b){const c=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){const d=a.slice(0,10<b?10:15),{unresolved:e,
unresolved_retry:h,guessed:l,guessed_retry:n,guessed_eachother:r}=c.rtcReq(d);c.is_rtc_peers_alive=e.length<d.length;yield Promise.all([c.prefetch(r,90),c.prefetch(e.concat(l,h,n),30),c.prefetch(d,25)])})}prefetch(a,b){const c=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){const d=1<=c.opts.maxHttpThread&&5>=c.opts.maxHttpThread?c.opts.maxHttpThread:3;for(const e of a){if(k.get(c.opts.id,e.sn))continue;for(;c.httpThread>=d&&(yield G(1E3),!k.get(c.opts.id,e.sn)););if(k.get(c.opts.id,
e.sn))continue;for(;c.opts.buffered()>b&&(yield G(1E3),!k.get(c.opts.id,e.sn)););if(k.get(c.opts.id,e.sn))continue;let h=c.tasks.get(e.sn);h||(h=new Promise((l,n)=>$jscomp.asyncExecutePromiseGeneratorFunction(function*(){try{c.httpThread++;const r=yield Promise.race(c.buildReq(e));return l(r)}catch(r){return n(r)}finally{c.httpThread--}})),c.tasks.set(e.sn,h))}})}rtcReq(a){this.rtcProvider||(this.rtcProvider=new aa(this.opts),this.rtcProvider.listen("buffer",e=>{D("rtc-buffer",e);if(e.data.id===this.opts.id){var h=
e.data.buffer.byteLength;e.newly?e.server?this.rtcServerDownload+=h:this.rtcClientDownload+=h:e.server?this.rtcServerDelayDownload+=h:this.rtcClientDelayDownload+=h}}).listen("buffer.recv",e=>{D("buffer.recv",e);e.data.id==this.opts.id&&(this.rtcTotalDownload+=e.data.data.byteLength,this.vstat())}));const b=this.rtcProvider.req(a),c=b.unresolved.map(e=>e.sn),d=b.guessed.map(e=>e.sn);a=a.filter(e=>!c.includes(e.sn)&&!d.includes(e.sn));a.length&&D("rtc-start",{id:this.opts.id,data:a});b.guessed.length&&
D("rtc-guess",{id:this.opts.id,data:b.guessed});return b}httpReq(a){const b=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){try{D("http-start",{id:b.opts.id,data:a});const c=yield b.httpProvider.req(a);c.cached||(b.httpTotalDownload+=c.data.byteLength);const d={id:b.opts.id,part:c.no,buffer:c.data,newly:c.newly};b.vstat();D("http-buffer",d);return d}catch(c){throw D("http-error",{id:b.opts.id,data:a}),c;}})}vstat(){const a=Date.now();2E3<a-this.lastReportTime&&(this.lastReportTime=
a,D("vstat",this.getStatData()))}getStatData(){return{httpTotalDownload:this.httpTotalDownload,rtcClientDownload:this.rtcClientDownload,rtcServerDownload:this.rtcServerDownload,rtcClientDelayDownload:this.rtcClientDelayDownload,rtcServerDelayDownload:this.rtcServerDelayDownload,rtcTotalDownload:this.rtcTotalDownload}}rtcPeers(){if(this.rtcProvider)return this.rtcProvider.getPeers()}rtcStats(){if(this.rtcProvider)return this.rtcProvider.getStats()}}class ea extends f{constructor(a){super();this.opts=
a;this.provider=new da(a)}nextN(a){var b=this.opts.fragments.slice(a.sn+1,a.sn+1+20);a=b.filter(c=>!k.get(this.opts.id,c.sn));b=b.length-a.length;if(5>a.length)return b;a.length&&this.provider.next(a,b);return b}getFragment(a){const b=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){b.nextN(a);const c=k.get(b.opts.id,a.sn);return c?c:b.provider.req(a)})}}var fa=Hls;const ha=a=>{const b=[];for(;!(b.unshift("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".charAt(a%
62)),a=Math.floor(a/62),0>=a););return b.join("")},ia=a=>{let b=2166136261;a=(new TextEncoder).encode(a);for(let c=0;c<a.length;c++)b=(b^a[c])>>>0,b=b+(b<<1)+(b<<4)+(b<<7)+(b<<8)+(b<<24)>>>0;return b},M={tracker:"wss://wss.p2sp.xyz:3060/ws/",mirrors:[{url:"",type:I.QUERY,fast:!0}],rtcConf:{iceServers:[{urls:"stun:stun.qq.com:8000"},{urls:"stun:stun.douyucdn.cn:18000"},{urls:"stun:stun.miwifi.com:3479"}]},maxHttpThread:2,statURL:"https://www.p2sp.xyz/home/stats",params:{site:'656ed7183cc97'}};class S{constructor(a,b){this.hls=a;this.opts=b;this.buf=this.t=0;const c=(d,e)=>{try{if(!this.config||e!=this.config.url||this.config.fragments.length!=d.length){var h=d.map(n=>({url:n.url,sn:n.sn,start:n.start,end:n.end?n.end:n.start+n.duration,duration:n.duration}));this.config=Object.assign({},b,{url:e,video:a.media,fragments:h,id:ha(ia(b.hashURL||e)),buffered:()=>this.cached_buffered_sec()});var l=t();this.hlsp2p=new ea(this.config);D("init",this.config,l)}}catch(n){console.error(n)}};
a.config.fLoader=this.buildLoader();if(a.bufferController.details&&a.bufferController.details.fragments)c(a.bufferController.details.fragments,a.bufferController.details.url);else a.on(fa.Events.LEVEL_LOADED,(d,e)=>{c(e.details.fragments,e.details.url)})}getFragment(a){const b=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){for(;yield G(20),!b.hlsp2p;);return b.hlsp2p.getFragment(a)})}buildLoader(){const a=this;class b{constructor(){this.stats={aborted:!1,loaded:0,total:0,chunkCount:0,
bwEstimate:0,retry:0,loading:{start:0,first:0,end:0},parsing:{start:0,end:0},buffering:{start:0,first:0,end:0}}}load(c,d,e){d=c.frag;const h=Date.now(),l=this.stats;l.loading.start=h;l.parsing.start=h;l.buffering.start=h;a.getFragment(d).then(n=>{const r=Date.now();l.loading.end=r;l.parsing.end=r;l.buffering.end=r;l.loaded+=n.buffer.byteLength;l.total+=n.buffer.byteLength;l.chunkCount+=1;l.bwEstimate=l.loaded/(r-h);n=n.buffer.slice(0);if(e.onProgress)e.onProgress(l,c,n);e.onSuccess({data:n,url:c.url},
l,c)}).catch(n=>{console.error(n);e.onError(n,c,l)})}destroy(){}abort(){this.stats.aborted=!0}}return b}buffered(){const a=this.hls.media;var b=0;if(a&&a.buffered.length){const c=a.currentTime;for(let d=0;d<a.buffered.length;d++){const e=a.buffered.start(d),h=a.buffered.end(d);c>=e&&c<=h&&(b=h-c,b=a.readyState>=a.HAVE_FUTURE_DATA?b:0)}}return b}cached_buffered_sec(){const a=Date.now();if(500>a-this.t)return this.buf;this.buf=this.buffered();this.t=a;return this.buf}static loadConfig(a){return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){try{const b=
yield(yield fetch(a)).json();return Object.assign({},M,b)}catch(b){return M}})}static Init(a,b,c){const d=this;return $jscomp.asyncExecutePromiseGeneratorFunction(function*(){let e;e=b?yield d.loadConfig(b):M;"function"==typeof c&&(e=c(e));return new d(a,e)})}}S.version="1.0.8";return window.HlsP2P=S});